// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/books.dart';
import 'api/core.dart';
import 'api/oc_observer.dart';
import 'api/user_books.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'third_party/ark_application/application.dart';
import 'third_party/ark_application/file_storage.dart';
import 'third_party/ark_application/file_storage/images.dart';
import 'third_party/ark_backend_api/creative_work/book.dart';
import 'third_party/ark_backend_api/creative_work/organization.dart';
import 'third_party/ark_backend_api/creative_work/person.dart';
import 'third_party/ark_backend_api/creative_work/subject.dart';
import 'third_party/ark_backend_api/creative_work/text_object.dart';
import 'third_party/ark_backend_api/personal_data/book_user_data.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ArkBooksPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkBooks;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_BooksObservableCollectionPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBooksObservableCollection;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_DApplicationPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDApplication;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_DPortalPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDPortal;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_FileProviderPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileProvider;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_FileStoragePtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileStorage;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_OcSubscriptionPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOCSubscription;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_RBookBindingPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookBinding;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_RBookSubscriptionPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookSubscription;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_UserBooksCollectionPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserBooksCollection;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ArkBooks
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkBooks(
          dynamic raw);

  @protected
  BooksObservableCollection
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBooksObservableCollection(
          dynamic raw);

  @protected
  DApplication
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDApplication(
          dynamic raw);

  @protected
  DPortal
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDPortal(
          dynamic raw);

  @protected
  FileProvider
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileProvider(
          dynamic raw);

  @protected
  FileStorage
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileStorage(
          dynamic raw);

  @protected
  OcSubscription
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOCSubscription(
          dynamic raw);

  @protected
  RBookBinding
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookBinding(
          dynamic raw);

  @protected
  RBookSubscription
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookSubscription(
          dynamic raw);

  @protected
  UserBooksCollection
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserBooksCollection(
          dynamic raw);

  @protected
  BooksObservableCollection
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBooksObservableCollection(
          dynamic raw);

  @protected
  UserBooksCollection
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserBooksCollection(
          dynamic raw);

  @protected
  ArkBooks
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkBooks(
          dynamic raw);

  @protected
  DApplication
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDApplication(
          dynamic raw);

  @protected
  DPortal
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDPortal(
          dynamic raw);

  @protected
  FileProvider
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileProvider(
          dynamic raw);

  @protected
  FileStorage
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileStorage(
          dynamic raw);

  @protected
  RBookBinding
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookBinding(
          dynamic raw);

  @protected
  FutureOr<void> Function(FlatEventBook)
      dco_decode_DartFn_Inputs_flat_event_book_Output_unit_AnyhowException(
          dynamic raw);

  @protected
  FutureOr<void> Function(FlatEventUserBook)
      dco_decode_DartFn_Inputs_flat_event_user_book_Output_unit_AnyhowException(
          dynamic raw);

  @protected
  FutureOr<void> Function(RBookEntityEvent)
      dco_decode_DartFn_Inputs_r_book_entity_event_Output_unit_AnyhowException(
          dynamic raw);

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  ArkBooks
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkBooks(
          dynamic raw);

  @protected
  BooksObservableCollection
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBooksObservableCollection(
          dynamic raw);

  @protected
  DApplication
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDApplication(
          dynamic raw);

  @protected
  DPortal
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDPortal(
          dynamic raw);

  @protected
  FileProvider
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileProvider(
          dynamic raw);

  @protected
  FileStorage
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileStorage(
          dynamic raw);

  @protected
  OcSubscription
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOCSubscription(
          dynamic raw);

  @protected
  RBookBinding
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookBinding(
          dynamic raw);

  @protected
  RBookSubscription
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookSubscription(
          dynamic raw);

  @protected
  UserBooksCollection
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserBooksCollection(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ApplicationConfig dco_decode_application_config(dynamic raw);

  @protected
  Book dco_decode_book(dynamic raw);

  @protected
  BookDraft dco_decode_book_draft(dynamic raw);

  @protected
  BookPredicate dco_decode_book_predicate(dynamic raw);

  @protected
  BookUpdate dco_decode_book_update(dynamic raw);

  @protected
  BookUserData dco_decode_book_user_data(dynamic raw);

  @protected
  BookUserDataDraft dco_decode_book_user_data_draft(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DPortal
      dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDPortal(
          dynamic raw);

  @protected
  RBookBinding
      dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookBinding(
          dynamic raw);

  @protected
  ApplicationConfig dco_decode_box_autoadd_application_config(dynamic raw);

  @protected
  Book dco_decode_box_autoadd_book(dynamic raw);

  @protected
  BookDraft dco_decode_box_autoadd_book_draft(dynamic raw);

  @protected
  BookUserData dco_decode_box_autoadd_book_user_data(dynamic raw);

  @protected
  ImageQuery dco_decode_box_autoadd_image_query(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  UserBook dco_decode_box_autoadd_user_book(dynamic raw);

  @protected
  FlatEventBook dco_decode_flat_event_book(dynamic raw);

  @protected
  FlatEventUserBook dco_decode_flat_event_user_book(dynamic raw);

  @protected
  ImageQuery dco_decode_image_query(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Book> dco_decode_list_book(dynamic raw);

  @protected
  List<Organization> dco_decode_list_organization(dynamic raw);

  @protected
  List<Person> dco_decode_list_person(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Subject> dco_decode_list_subject(dynamic raw);

  @protected
  List<TextObject> dco_decode_list_text_object(dynamic raw);

  @protected
  List<UserBook> dco_decode_list_user_book(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DPortal?
      dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDPortal(
          dynamic raw);

  @protected
  RBookBinding?
      dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookBinding(
          dynamic raw);

  @protected
  BookUserData? dco_decode_opt_box_autoadd_book_user_data(dynamic raw);

  @protected
  ImageQuery? dco_decode_opt_box_autoadd_image_query(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  Organization dco_decode_organization(dynamic raw);

  @protected
  Person dco_decode_person(dynamic raw);

  @protected
  PersonDraft dco_decode_person_draft(dynamic raw);

  @protected
  PersonFilter dco_decode_person_filter(dynamic raw);

  @protected
  RBookEntityEvent dco_decode_r_book_entity_event(dynamic raw);

  @protected
  Subject dco_decode_subject(dynamic raw);

  @protected
  TextObject dco_decode_text_object(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserBook dco_decode_user_book(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ArkBooks
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkBooks(
          SseDeserializer deserializer);

  @protected
  BooksObservableCollection
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBooksObservableCollection(
          SseDeserializer deserializer);

  @protected
  DApplication
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDApplication(
          SseDeserializer deserializer);

  @protected
  DPortal
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDPortal(
          SseDeserializer deserializer);

  @protected
  FileProvider
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileProvider(
          SseDeserializer deserializer);

  @protected
  FileStorage
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileStorage(
          SseDeserializer deserializer);

  @protected
  OcSubscription
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOCSubscription(
          SseDeserializer deserializer);

  @protected
  RBookBinding
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookBinding(
          SseDeserializer deserializer);

  @protected
  RBookSubscription
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookSubscription(
          SseDeserializer deserializer);

  @protected
  UserBooksCollection
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserBooksCollection(
          SseDeserializer deserializer);

  @protected
  BooksObservableCollection
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBooksObservableCollection(
          SseDeserializer deserializer);

  @protected
  UserBooksCollection
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserBooksCollection(
          SseDeserializer deserializer);

  @protected
  ArkBooks
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkBooks(
          SseDeserializer deserializer);

  @protected
  DApplication
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDApplication(
          SseDeserializer deserializer);

  @protected
  DPortal
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDPortal(
          SseDeserializer deserializer);

  @protected
  FileProvider
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileProvider(
          SseDeserializer deserializer);

  @protected
  FileStorage
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileStorage(
          SseDeserializer deserializer);

  @protected
  RBookBinding
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookBinding(
          SseDeserializer deserializer);

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  ArkBooks
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkBooks(
          SseDeserializer deserializer);

  @protected
  BooksObservableCollection
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBooksObservableCollection(
          SseDeserializer deserializer);

  @protected
  DApplication
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDApplication(
          SseDeserializer deserializer);

  @protected
  DPortal
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDPortal(
          SseDeserializer deserializer);

  @protected
  FileProvider
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileProvider(
          SseDeserializer deserializer);

  @protected
  FileStorage
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileStorage(
          SseDeserializer deserializer);

  @protected
  OcSubscription
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOCSubscription(
          SseDeserializer deserializer);

  @protected
  RBookBinding
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookBinding(
          SseDeserializer deserializer);

  @protected
  RBookSubscription
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookSubscription(
          SseDeserializer deserializer);

  @protected
  UserBooksCollection
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserBooksCollection(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ApplicationConfig sse_decode_application_config(SseDeserializer deserializer);

  @protected
  Book sse_decode_book(SseDeserializer deserializer);

  @protected
  BookDraft sse_decode_book_draft(SseDeserializer deserializer);

  @protected
  BookPredicate sse_decode_book_predicate(SseDeserializer deserializer);

  @protected
  BookUpdate sse_decode_book_update(SseDeserializer deserializer);

  @protected
  BookUserData sse_decode_book_user_data(SseDeserializer deserializer);

  @protected
  BookUserDataDraft sse_decode_book_user_data_draft(
      SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DPortal
      sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDPortal(
          SseDeserializer deserializer);

  @protected
  RBookBinding
      sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookBinding(
          SseDeserializer deserializer);

  @protected
  ApplicationConfig sse_decode_box_autoadd_application_config(
      SseDeserializer deserializer);

  @protected
  Book sse_decode_box_autoadd_book(SseDeserializer deserializer);

  @protected
  BookDraft sse_decode_box_autoadd_book_draft(SseDeserializer deserializer);

  @protected
  BookUserData sse_decode_box_autoadd_book_user_data(
      SseDeserializer deserializer);

  @protected
  ImageQuery sse_decode_box_autoadd_image_query(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  UserBook sse_decode_box_autoadd_user_book(SseDeserializer deserializer);

  @protected
  FlatEventBook sse_decode_flat_event_book(SseDeserializer deserializer);

  @protected
  FlatEventUserBook sse_decode_flat_event_user_book(
      SseDeserializer deserializer);

  @protected
  ImageQuery sse_decode_image_query(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Book> sse_decode_list_book(SseDeserializer deserializer);

  @protected
  List<Organization> sse_decode_list_organization(SseDeserializer deserializer);

  @protected
  List<Person> sse_decode_list_person(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Subject> sse_decode_list_subject(SseDeserializer deserializer);

  @protected
  List<TextObject> sse_decode_list_text_object(SseDeserializer deserializer);

  @protected
  List<UserBook> sse_decode_list_user_book(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DPortal?
      sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDPortal(
          SseDeserializer deserializer);

  @protected
  RBookBinding?
      sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookBinding(
          SseDeserializer deserializer);

  @protected
  BookUserData? sse_decode_opt_box_autoadd_book_user_data(
      SseDeserializer deserializer);

  @protected
  ImageQuery? sse_decode_opt_box_autoadd_image_query(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Organization sse_decode_organization(SseDeserializer deserializer);

  @protected
  Person sse_decode_person(SseDeserializer deserializer);

  @protected
  PersonDraft sse_decode_person_draft(SseDeserializer deserializer);

  @protected
  PersonFilter sse_decode_person_filter(SseDeserializer deserializer);

  @protected
  RBookEntityEvent sse_decode_r_book_entity_event(SseDeserializer deserializer);

  @protected
  Subject sse_decode_subject(SseDeserializer deserializer);

  @protected
  TextObject sse_decode_text_object(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserBook sse_decode_user_book(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkBooks(
          ArkBooks self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBooksObservableCollection(
          BooksObservableCollection self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDApplication(
          DApplication self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDPortal(
          DPortal self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileProvider(
          FileProvider self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileStorage(
          FileStorage self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOCSubscription(
          OcSubscription self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookBinding(
          RBookBinding self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookSubscription(
          RBookSubscription self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserBooksCollection(
          UserBooksCollection self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBooksObservableCollection(
          BooksObservableCollection self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserBooksCollection(
          UserBooksCollection self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkBooks(
          ArkBooks self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDApplication(
          DApplication self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDPortal(
          DPortal self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileProvider(
          FileProvider self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileStorage(
          FileStorage self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookBinding(
          RBookBinding self, SseSerializer serializer);

  @protected
  void sse_encode_DartFn_Inputs_flat_event_book_Output_unit_AnyhowException(
      FutureOr<void> Function(FlatEventBook) self, SseSerializer serializer);

  @protected
  void
      sse_encode_DartFn_Inputs_flat_event_user_book_Output_unit_AnyhowException(
          FutureOr<void> Function(FlatEventUserBook) self,
          SseSerializer serializer);

  @protected
  void sse_encode_DartFn_Inputs_r_book_entity_event_Output_unit_AnyhowException(
      FutureOr<void> Function(RBookEntityEvent) self, SseSerializer serializer);

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkBooks(
          ArkBooks self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBooksObservableCollection(
          BooksObservableCollection self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDApplication(
          DApplication self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDPortal(
          DPortal self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileProvider(
          FileProvider self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileStorage(
          FileStorage self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOCSubscription(
          OcSubscription self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookBinding(
          RBookBinding self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookSubscription(
          RBookSubscription self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserBooksCollection(
          UserBooksCollection self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_application_config(
      ApplicationConfig self, SseSerializer serializer);

  @protected
  void sse_encode_book(Book self, SseSerializer serializer);

  @protected
  void sse_encode_book_draft(BookDraft self, SseSerializer serializer);

  @protected
  void sse_encode_book_predicate(BookPredicate self, SseSerializer serializer);

  @protected
  void sse_encode_book_update(BookUpdate self, SseSerializer serializer);

  @protected
  void sse_encode_book_user_data(BookUserData self, SseSerializer serializer);

  @protected
  void sse_encode_book_user_data_draft(
      BookUserDataDraft self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDPortal(
          DPortal self, SseSerializer serializer);

  @protected
  void
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookBinding(
          RBookBinding self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_application_config(
      ApplicationConfig self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_book(Book self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_book_draft(
      BookDraft self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_book_user_data(
      BookUserData self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_image_query(
      ImageQuery self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_user_book(
      UserBook self, SseSerializer serializer);

  @protected
  void sse_encode_flat_event_book(FlatEventBook self, SseSerializer serializer);

  @protected
  void sse_encode_flat_event_user_book(
      FlatEventUserBook self, SseSerializer serializer);

  @protected
  void sse_encode_image_query(ImageQuery self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_book(List<Book> self, SseSerializer serializer);

  @protected
  void sse_encode_list_organization(
      List<Organization> self, SseSerializer serializer);

  @protected
  void sse_encode_list_person(List<Person> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_subject(List<Subject> self, SseSerializer serializer);

  @protected
  void sse_encode_list_text_object(
      List<TextObject> self, SseSerializer serializer);

  @protected
  void sse_encode_list_user_book(List<UserBook> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
      sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDPortal(
          DPortal? self, SseSerializer serializer);

  @protected
  void
      sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookBinding(
          RBookBinding? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_book_user_data(
      BookUserData? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_image_query(
      ImageQuery? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer);

  @protected
  void sse_encode_organization(Organization self, SseSerializer serializer);

  @protected
  void sse_encode_person(Person self, SseSerializer serializer);

  @protected
  void sse_encode_person_draft(PersonDraft self, SseSerializer serializer);

  @protected
  void sse_encode_person_filter(PersonFilter self, SseSerializer serializer);

  @protected
  void sse_encode_r_book_entity_event(
      RBookEntityEvent self, SseSerializer serializer);

  @protected
  void sse_encode_subject(Subject self, SseSerializer serializer);

  @protected
  void sse_encode_text_object(TextObject self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_book(UserBook self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkBooks(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkBooks(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkBooks(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkBooks(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBooksObservableCollection(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBooksObservableCollection(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBooksObservableCollection(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBooksObservableCollection(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDApplication(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDApplication(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDApplication(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDApplication(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDPortal(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDPortal(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDPortal(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDPortal(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileProvider(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileProvider(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileProvider(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileProvider(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileStorage(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileStorage(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileStorage(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileStorage(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOCSubscription(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOCSubscription(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOCSubscription(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOCSubscription(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookBinding(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookBinding(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookBinding(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookBinding(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookSubscription(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookSubscription(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookSubscription(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookSubscription(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserBooksCollection(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserBooksCollection(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserBooksCollection(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserBooksCollection(
              ptr);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkBooks(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkBooks(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBooksObservableCollection(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBooksObservableCollection(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDApplication(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDApplication(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDPortal(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDPortal(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileProvider(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileProvider(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileStorage(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileStorage(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOCSubscription(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOCSubscription(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookBinding(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookBinding(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookSubscription(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRBookSubscription(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserBooksCollection(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserBooksCollection(
          int ptr);
}
