// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import '../third_party/ark_application/file_storage/images.dart';
import '../third_party/ark_backend_api/creative_work/book.dart';
import '../third_party/ark_backend_api/creative_work/organization.dart';
import '../third_party/ark_backend_api/creative_work/person.dart';
import '../third_party/ark_backend_api/creative_work/subject.dart';
import '../third_party/ark_backend_api/creative_work/text_object.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ArkBooks>>
abstract class ArkBooks implements RustOpaqueInterface {
  Future<String?> create({required BookDraft draft});

  Future<BooksCollection> createCollection();

  Future<UserBooksCollection> createUserCollection();

  Future<void> delete({required String id});

  Future<Uint8List> getBook({required String urn});

  Future<String> getBookStr({required String urn});

  Future<Uint8List?> getCover({required String urn, ImageParams? params});

  Future<void> storeEpubBook({required String path});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BookSubscription>>
abstract class BookSubscription implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BooksCollection>>
abstract class BooksCollection implements RustOpaqueInterface {
  Future<BookSubscription> subscribe(
      {required FutureOr<void> Function(List<Book>) f});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UserBookSubscription>>
abstract class UserBookSubscription implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UserBooksCollection>>
abstract class UserBooksCollection implements RustOpaqueInterface {
  Future<UserBookSubscription> subscribe(
      {required FutureOr<void> Function(List<UserBook>) f});
}
