// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/ark_application/file_storage/images.dart';
import '../third_party/ark_backend_api/creative_work/book.dart';
import '../third_party/ark_backend_api/creative_work/organization.dart';
import '../third_party/ark_backend_api/creative_work/person.dart';
import '../third_party/ark_backend_api/creative_work/subject.dart';
import '../third_party/ark_backend_api/creative_work/text_object.dart';
import 'oc_observer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'user_books.dart';
part 'books.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DartBookFlatOCObserver`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `reset`, `update`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ArkBooks>>
abstract class ArkBooks implements RustOpaqueInterface {
  Future<String?> create({required BookDraft draft});

  Future<BooksObservableCollection> createCollection();

  Future<UserBooksCollection> createUserCollection();

  Future<void> delete({required String id});

  Future<Uint8List> getBook({required String urn});

  Future<Uint8List?> getCover({required String urn, ImageParams? params});

  Future<void> setCompleted({required bool completed, required String bookId});

  Future<void> storeEpubBook({required String path});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BooksObservableCollection>>
abstract class BooksObservableCollection implements RustOpaqueInterface {
  Future<OcSubscription> subscribe(
      {required FutureOr<void> Function(FlatEventBook) callback});
}

@freezed
sealed class FlatEventBook with _$FlatEventBook {
  const FlatEventBook._();

  const factory FlatEventBook.beginTasnsaction() =
      FlatEventBook_BeginTasnsaction;
  const factory FlatEventBook.finishTransaction() =
      FlatEventBook_FinishTransaction;
  const factory FlatEventBook.reset({
    required List<Book> items,
  }) = FlatEventBook_Reset;
  const factory FlatEventBook.delete({
    required BigInt start,
    required BigInt end,
  }) = FlatEventBook_Delete;
  const factory FlatEventBook.insert({
    required BigInt index,
    required List<Book> items,
  }) = FlatEventBook_Insert;
  const factory FlatEventBook.update({
    required BigInt index,
    required Book item,
  }) = FlatEventBook_Update;
  const factory FlatEventBook.move({
    required BigInt start,
    required BigInt end,
    required PlatformInt64 offset,
  }) = FlatEventBook_Move;
}
