// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/ark_backend_api/creative_work/book.dart';
import '../third_party/ark_backend_api/creative_work/organization.dart';
import '../third_party/ark_backend_api/creative_work/person.dart';
import '../third_party/ark_backend_api/creative_work/subject.dart';
import '../third_party/ark_backend_api/creative_work/text_object.dart';
import '../third_party/ark_backend_api/personal_data/book_user_data.dart';
import 'oc_observer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'user_books.dart';
part 'books.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `drop`, `new`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DartBookFlatOCObserver`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `reset`, `update`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ArkBooks>>
abstract class ArkBooks implements RustOpaqueInterface {
  Future<RBookBinding?> bookBinding({required String id});

  Future<String?> create({required BookDraft draft});

  Future<BooksObservableCollection> createCollection();

  Future<UserBooksCollection> createUserCollection();

  Future<void> delete({required String id});

  Future<Uint8List> getBook({required String urn});

  Future<void> setCompleted({required bool completed, required String bookId});

  Future<void> storeEpubBook({required String path});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BooksObservableCollection>>
abstract class BooksObservableCollection implements RustOpaqueInterface {
  Future<OcSubscription> subscribe(
      {required FutureOr<void> Function(FlatEventBook) callback});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RBookBinding>>
abstract class RBookBinding implements RustOpaqueInterface {
  Future<void> delete();

  Future<UserBook> getModel();

  Future<void> setCompleted({required bool completed});

  Future<RBookSubscription> subscribe(
      {required FutureOr<void> Function(RBookEntityEvent) callback});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RBookSubscription>>
abstract class RBookSubscription implements RustOpaqueInterface {}

@freezed
sealed class FlatEventBook with _$FlatEventBook {
  const FlatEventBook._();

  const factory FlatEventBook.beginTasnsaction() =
      FlatEventBook_BeginTasnsaction;
  const factory FlatEventBook.finishTransaction() =
      FlatEventBook_FinishTransaction;
  const factory FlatEventBook.reset({
    required List<Book> items,
  }) = FlatEventBook_Reset;
  const factory FlatEventBook.delete({
    required BigInt start,
    required BigInt end,
  }) = FlatEventBook_Delete;
  const factory FlatEventBook.insert({
    required BigInt index,
    required List<Book> items,
  }) = FlatEventBook_Insert;
  const factory FlatEventBook.update({
    required BigInt index,
    required Book item,
  }) = FlatEventBook_Update;
  const factory FlatEventBook.move({
    required BigInt start,
    required BigInt end,
    required PlatformInt64 offset,
  }) = FlatEventBook_Move;
}

@freezed
sealed class RBookEntityEvent with _$RBookEntityEvent {
  const RBookEntityEvent._();

  const factory RBookEntityEvent.updated(
    UserBook field0,
  ) = RBookEntityEvent_Updated;
  const factory RBookEntityEvent.deleted() = RBookEntityEvent_Deleted;
}
