// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'books.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Application>>
abstract class Application implements RustOpaqueInterface {
  Future<Portal?> mainPortal();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Application> newInstance({required AppConfig config}) =>
      RustLib.instance.api.crateApiCoreApplicationNew(config: config);

  Future<void> start();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Portal>>
abstract class Portal implements RustOpaqueInterface {
  Future<ArkBooks> booksCtr();
}

class AppConfig {
  final String storageDir;

  const AppConfig({
    required this.storageDir,
  });

  @override
  int get hashCode => storageDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppConfig &&
          runtimeType == other.runtimeType &&
          storageDir == other.storageDir;
}
