// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/ark_application/application.dart';
import 'books.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DApplication>>
abstract class DApplication implements RustOpaqueInterface {
  Future<Portal?> mainPortal();

  static Future<DApplication> run({required ApplicationConfig config}) =>
      RustLib.instance.api.crateApiCoreDApplicationRun(config: config);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Portal>>
abstract class Portal implements RustOpaqueInterface {
  Future<ArkBooks> booksCtr();
}
