// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/ark_application/application.dart';
import '../third_party/ark_application/infrastructure/file_storage/images.dart';
import 'books.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DApplication>>
abstract class DApplication implements RustOpaqueInterface {
  Future<DPortal?> mainPortal();

  static Future<DApplication> run({required ApplicationConfig config}) =>
      RustLib.instance.api.crateApiCoreDApplicationRun(config: config);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DPortal>>
abstract class DPortal implements RustOpaqueInterface {
  ArkBooks booksCtr();

  FileProvider fileProvider();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FileProvider>>
abstract class FileProvider implements RustOpaqueInterface {
  Future<Uint8List?> getImage({required String urn, ImageQuery? params});
}
