// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/ark_backend_api/creative_work/book.dart';
import '../third_party/ark_backend_api/creative_work/organization.dart';
import '../third_party/ark_backend_api/creative_work/person.dart';
import '../third_party/ark_backend_api/creative_work/subject.dart';
import '../third_party/ark_backend_api/creative_work/text_object.dart';
import '../third_party/ark_backend_api/personal_data/book_user_data.dart';
import 'oc_observer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'user_books.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DartUserBookFlatOCObserver`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `reset`, `update`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UserBooksCollection>>
abstract class UserBooksCollection implements RustOpaqueInterface {
  Future<OcSubscription> subscribe(
      {required FutureOr<void> Function(FlatEventUserBook) callback});
}

@freezed
sealed class FlatEventUserBook with _$FlatEventUserBook {
  const FlatEventUserBook._();

  const factory FlatEventUserBook.beginTasnsaction() =
      FlatEventUserBook_BeginTasnsaction;
  const factory FlatEventUserBook.finishTransaction() =
      FlatEventUserBook_FinishTransaction;
  const factory FlatEventUserBook.reset({
    required List<UserBook> items,
  }) = FlatEventUserBook_Reset;
  const factory FlatEventUserBook.delete({
    required BigInt start,
    required BigInt end,
  }) = FlatEventUserBook_Delete;
  const factory FlatEventUserBook.insert({
    required BigInt index,
    required List<UserBook> items,
  }) = FlatEventUserBook_Insert;
  const factory FlatEventUserBook.update({
    required BigInt index,
    required UserBook item,
  }) = FlatEventUserBook_Update;
  const factory FlatEventUserBook.move({
    required BigInt start,
    required BigInt end,
    required PlatformInt64 offset,
  }) = FlatEventUserBook_Move;
}

class UserBook {
  final Book book;
  final String portalId;
  final BookUserData? userData;

  const UserBook({
    required this.book,
    required this.portalId,
    this.userData,
  });

  @override
  int get hashCode => book.hashCode ^ portalId.hashCode ^ userData.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserBook &&
          runtimeType == other.runtimeType &&
          book == other.book &&
          portalId == other.portalId &&
          userData == other.userData;
}
